version: '2'
services:
  db:
    image: mysql/mysql-server:5.5
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: remember
    
  nemo:
    build: .
    image: syntithenai/nemo
    restart: always
    volumes:
      - "./:/usr/src/app/"
    environment:
      #VIRTUAL_HOST: syntithenai.com
      #LETSENCRYPT_HOST: syntithenai.com
      #LETSENCRYPT_EMAIL: stever@syntithenai.com
      DB_HOST: db
      MYSQL_ROOT_PASSWORD: remember
      DB_DATABASE: nemo
    ports:
      - "80:3000"
